@DientesLimpios.API_HostAddress = http://localhost:5249/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/01994024-76A2-73CF-8A04-FC5651A19A83
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Consultorio B"
}

###

PUT {{DientesLimpios.API_HostAddress}}/01994c2f-036d-765e-9840-224deb3b2371
Content-Type: application/json

{
  "nombre": "Consultorio B - Actualizado"
}