@DientesLimpios.API_HostAddress = https://localhost:7279/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/01994024-76a2-73cf-8a04-fc5651a19a83
Accept: application/json
Authorization: Bearer CfDJ8Nf8l7TxidZKoKrI9bfa2oq-FsYHcTsXXL2jxy1HWoI1NdywZWom1wiX-4PwPN5hwk5QdR7MLivQLx8oi0jYt3HE8_c6---3Xh9M4IK2qPF6WY9qmwmaFvEKZe8y9HcSp-e_wJv-NGalLS7WZKzBswfyuEX2ORJZRwGLwRp2aHIXcSvZ5KNJG9LmG0DMbLnTPsaiSNtrO_bXJ9PUgLmgEqNp6OWERmczlb4JKhfdgGJrtyRPg201c80oB8zPtGM5hZxkAne24R67ze1rZT57IvfGa1RO5KhYH9yUSwKiKifqFfAkAcwdQDd96dtBehy4GiXTuqpcbLRnsRTh5WEbEg_OmKgN8OhedTJKPpvtB-64w7guWkoyWFOHue4pSaE_z8HTurCOy-4ZjNdls0M3eSzx9G9qjCGlrH0Kp1ALOk3WFnCbVnMO13fbEuK7yLSfaA5WfBktR2pokYqwbMzizLVIvyS2--L0Ug8RIe1rdAwS27Rsg9cPsGNGQp4pdY3rxP1b7XEbis79Yi6z4FxGv5QW3UjmqTV3nKhcgzIv05rnM1LMPe1k99WuhxLJ4UXHKYDO76zZmVsIaAjw1UN5NksAk1-DgvJrYYNqPxjYkRn07zNVf15htFPAneSO2oLYgmBBSaCJQfHutVxihl9GFickPNwaGwssiddyCwbouBdPM9KepuzwBH142sk1Oz4BI653GCWIXq_-Zj5ZKa98rvym5-Ft5AJnJRdTO9J0IN87


###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8Nf8l7TxidZKoKrI9bfa2oq-FsYHcTsXXL2jxy1HWoI1NdywZWom1wiX-4PwPN5hwk5QdR7MLivQLx8oi0jYt3HE8_c6---3Xh9M4IK2qPF6WY9qmwmaFvEKZe8y9HcSp-e_wJv-NGalLS7WZKzBswfyuEX2ORJZRwGLwRp2aHIXcSvZ5KNJG9LmG0DMbLnTPsaiSNtrO_bXJ9PUgLmgEqNp6OWERmczlb4JKhfdgGJrtyRPg201c80oB8zPtGM5hZxkAne24R67ze1rZT57IvfGa1RO5KhYH9yUSwKiKifqFfAkAcwdQDd96dtBehy4GiXTuqpcbLRnsRTh5WEbEg_OmKgN8OhedTJKPpvtB-64w7guWkoyWFOHue4pSaE_z8HTurCOy-4ZjNdls0M3eSzx9G9qjCGlrH0Kp1ALOk3WFnCbVnMO13fbEuK7yLSfaA5WfBktR2pokYqwbMzizLVIvyS2--L0Ug8RIe1rdAwS27Rsg9cPsGNGQp4pdY3rxP1b7XEbis79Yi6z4FxGv5QW3UjmqTV3nKhcgzIv05rnM1LMPe1k99WuhxLJ4UXHKYDO76zZmVsIaAjw1UN5NksAk1-DgvJrYYNqPxjYkRn07zNVf15htFPAneSO2oLYgmBBSaCJQfHutVxihl9GFickPNwaGwssiddyCwbouBdPM9KepuzwBH142sk1Oz4BI653GCWIXq_-Zj5ZKa98rvym5-Ft5AJnJRdTO9J0IN87

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8Nf8l7TxidZKoKrI9bfa2oq-FsYHcTsXXL2jxy1HWoI1NdywZWom1wiX-4PwPN5hwk5QdR7MLivQLx8oi0jYt3HE8_c6---3Xh9M4IK2qPF6WY9qmwmaFvEKZe8y9HcSp-e_wJv-NGalLS7WZKzBswfyuEX2ORJZRwGLwRp2aHIXcSvZ5KNJG9LmG0DMbLnTPsaiSNtrO_bXJ9PUgLmgEqNp6OWERmczlb4JKhfdgGJrtyRPg201c80oB8zPtGM5hZxkAne24R67ze1rZT57IvfGa1RO5KhYH9yUSwKiKifqFfAkAcwdQDd96dtBehy4GiXTuqpcbLRnsRTh5WEbEg_OmKgN8OhedTJKPpvtB-64w7guWkoyWFOHue4pSaE_z8HTurCOy-4ZjNdls0M3eSzx9G9qjCGlrH0Kp1ALOk3WFnCbVnMO13fbEuK7yLSfaA5WfBktR2pokYqwbMzizLVIvyS2--L0Ug8RIe1rdAwS27Rsg9cPsGNGQp4pdY3rxP1b7XEbis79Yi6z4FxGv5QW3UjmqTV3nKhcgzIv05rnM1LMPe1k99WuhxLJ4UXHKYDO76zZmVsIaAjw1UN5NksAk1-DgvJrYYNqPxjYkRn07zNVf15htFPAneSO2oLYgmBBSaCJQfHutVxihl9GFickPNwaGwssiddyCwbouBdPM9KepuzwBH142sk1Oz4BI653GCWIXq_-Zj5ZKa98rvym5-Ft5AJnJRdTO9J0IN87

{
  "nombre": "Consultorio E"
}

###

PUT {{DientesLimpios.API_HostAddress}}/0199A7F7-6899-7182-931C-BF647B474B23
Content-Type: application/json
Authorization: Bearer CfDJ8Nf8l7TxidZKoKrI9bfa2oq-FsYHcTsXXL2jxy1HWoI1NdywZWom1wiX-4PwPN5hwk5QdR7MLivQLx8oi0jYt3HE8_c6---3Xh9M4IK2qPF6WY9qmwmaFvEKZe8y9HcSp-e_wJv-NGalLS7WZKzBswfyuEX2ORJZRwGLwRp2aHIXcSvZ5KNJG9LmG0DMbLnTPsaiSNtrO_bXJ9PUgLmgEqNp6OWERmczlb4JKhfdgGJrtyRPg201c80oB8zPtGM5hZxkAne24R67ze1rZT57IvfGa1RO5KhYH9yUSwKiKifqFfAkAcwdQDd96dtBehy4GiXTuqpcbLRnsRTh5WEbEg_OmKgN8OhedTJKPpvtB-64w7guWkoyWFOHue4pSaE_z8HTurCOy-4ZjNdls0M3eSzx9G9qjCGlrH0Kp1ALOk3WFnCbVnMO13fbEuK7yLSfaA5WfBktR2pokYqwbMzizLVIvyS2--L0Ug8RIe1rdAwS27Rsg9cPsGNGQp4pdY3rxP1b7XEbis79Yi6z4FxGv5QW3UjmqTV3nKhcgzIv05rnM1LMPe1k99WuhxLJ4UXHKYDO76zZmVsIaAjw1UN5NksAk1-DgvJrYYNqPxjYkRn07zNVf15htFPAneSO2oLYgmBBSaCJQfHutVxihl9GFickPNwaGwssiddyCwbouBdPM9KepuzwBH142sk1Oz4BI653GCWIXq_-Zj5ZKa98rvym5-Ft5AJnJRdTO9J0IN87

{
  "nombre": "Consultorio E - Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/01995b3a-f53a-714d-b07c-8cf5b3d8ff8e
Accept: application/json